default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: simple_scraper_development

test:
  <<: *default
  database: simple_scraper_test

production:
  <<: *default
  database: simple_scraper_production
  username: simple_scraper
  password: <%= ENV["SIMPLE_SCRAPER_DATABASE_PASSWORD"] %>
